language: ruby
rvm:
  - 2.4.1
  - 2.5.1
before_script:
  - bundle exec danger
script:
  - bundle exec rake lint
install:
  - bundle
  - ssh-keyscan -t $TRAVIS_SSH_KEY_TYPES -H $PRODUCTION_HOST 2>&1 | tee -a $HOME/.ssh/known_hosts
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
cache: bundler
notifications:
  email: false
addons:
  ssh_known_hosts: $PRODUCTION_HOST
deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
