language: ruby
rvm:
  - ruby-head
before_script:
  - bundle exec danger
script:
  - bundle exec rake lint
install:
  - bundle update --bundler
  - bundle
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
cache: bundler
notifications:
  email: false
addons:
  ssh_known_hosts: yusuke.cloud
deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
