language: ruby
rvm:
- 2.4.1
script:
- bundle exec rake lint
deploy:
  - provider: script
    skip_cleanup: true
    script:
      - rsync -avuze "ssh -i ~/.ssh/linode" --delete _site yusuke-bot@${STAGING_IP}:~/
      - ssh -ti ~/.ssh/linode yusuke-bot@${STAGING_IP} "sudo rsync -avuz --delete _site/ /var/www/${STAGING_HOST}/ && rm -rf _site"
    on:
      branches: develop
  - provider: script
    skip_cleanup: true
    script:
      - rsync -avuze "ssh -i ~/.ssh/linode" --delete _site yusuke-bot@${PRODUCTION_IP}:~/
      - ssh -ti ~/.ssh/linode yusuke-bot@${PRODUCTION_IP} "sudo rsync -avuz --delete _site/ /var/www/${PRODUCTION_HOST}/ && rm -rf _site"
    on:
      branches: master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
cache: bundler
notifications:
  email: false
before_install:
  - openssl aes-256-cbc -K $encrypted_bd89d04f99c0_key -iv $encrypted_bd89d04f99c0_iv -in deploy-key.enc -out deploy-key -d
  - mv deploy-key ~/.ssh/linode
