language: ruby
rvm:
- 2.4.1
script:
- bundle exec rake lint
deploy:
  - provider: script
    skip_cleanup: true
    script: bash script/deploy.sh ${STAGING_IP} ${STAGING_HOST}
    on:
      branch: develop
  - provider: script
    skip_cleanup: true
    script: bash script/deploy.sh ${PRODUCTION_IP} ${PRODUCTION_HOST}
    on:
      branch: master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
cache: bundler
notifications:
  email: false
before_install:
  - openssl aes-256-cbc -K $encrypted_bd89d04f99c0_key -iv $encrypted_bd89d04f99c0_iv -in deploy-key.enc -out deploy-key -d
  - mv deploy-key ~/.ssh/linode
