language: ruby
rvm:
- 2.4.1
script:
- bundle exec rake lint
deploy:
  provider: script
  script: bundle exec rake deploy
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^staging|production
branches:
  except:
  - staging
  - production
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
cache: bundler
notifications:
  email: false
before_install:
  - openssl aes-256-cbc -K $encrypted_bd89d04f99c0_key -iv $encrypted_bd89d04f99c0_iv -in deploy-key.enc -out deploy-key -d
  - mv deploy-key ~/.ssh/linode
