theme: minima
title: Yusuke on the Cloud
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://yusuke.cloud/"
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - Dangerfile
  - scripts
  - vendor
  - deploy-key.enc
  - deploy-key.pub
sass:
  style: compressed
plugins:
  - jekyll-archives
  - jekyll-feed
  - jekyll-paginate
permalink: /blog/:year/:month/:day/:title/
paginate: 5
paginate_path: "/blog/:num/"
markdown: kramdown
