theme: minima
title: Yusuke on the Cloud
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - script
  - vendor
  - deploy-key.enc
  - deploy-key.pub
sass:
  style: compressed
plugins:
  - jekyll-archives
