name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Dokku deploy
      uses: vitalyliber/dokku-github-action@v6.0
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        HOST: yusuke.cloud
        PROJECT: weblog
    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v2
      with:
        repo: junkpiano/junkpiano.github.io
        target_branch: master
        build_dir: public
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_TOKEN}}