name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Dokku deploy
      uses: dokku/github-action@v1.0.2
      with:
        ssh_private_key: ${{ secrets.PRIVATE_KEY }}
        git_remote_url: "ssh://dokku@yusuke.cloud:22/weblog"
